# Preprocessing

## Import Library

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

pd.set_option("display.max_columns", None)

## Load Dataset

In [3]:
df = pd.read_csv("../Datasheet/OBD-Anomaly-Detection/dataset/all_dataset.csv")

print(df.shape)

df.head()

(1030, 49)

,lat,lng,name,source_file,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,MAF,DateTime,Speed,GPH,LPH,Unnamed: 12,KPL,Unnamed: 14,CO2 Emissions,timeStamp (N),DateTime (S),altitude (N),latitude (N),longitude (N),readings (M),vehicleId (S),Time,Speed.1,note,name,rpm,name.1,rpm.1,time,speed,894,RPM,speed.1,time.1,speed.2,Unnamed: 15,Speed (km/h),Engine RPM,Unnamed: 19,name,Unnamed: 13
0,33.997577,71.491204,6:44:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,33.997541,71.490413,6:44:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,33.997589,71.489618,6:44:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,33.997596,71.489163,6:45:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,33.997798,71.483814,6:45:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Informasi Dataset

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 49 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   lat            601 non-null    float64
 1   lng            601 non-null    float64
 2   name           243 non-null    object
 3   source_file    1030 non-null   object
 4   Unnamed: 3     0 non-null      float64
 5   Unnamed: 4     0 non-null      float64
 6   Unnamed: 5     34 non-null     float64
 7   Unnamed: 6     95 non-null     object
 8   Unnamed: 7     95 non-null     float64
 9   Unnamed: 8     95 non-null     float64
 10  Unnamed: 9     0 non-null      float64
 11  Unnamed: 10    0 non-null      float64
 12  Unnamed: 11    0 non-null      float64
 13  MAF            88 non-null     float64
 14  DateTime       88 non-null     object
 15  Speed          201 non-null    float64
 16  GPH            44 non-null     float64
 17  LPH            44 non-null     float64
 18  Unnamed: 12    2 non-null      object
 19  KPL            44 non-null     float64
 20  Unnamed: 14    34 non-null     float64
 21  CO2 Emissions  44 non-null     float64
 22  timeStamp (N)  234 non-null    float64
 23  DateTime (S)   234 non-null    object
 24  altitude (N)   234 non-null    float64
 25  latitude (N)   295 non-null    float64
 26  longitude (N)  329 non-null    object
 27  readings (M)   374 non-null    object
 28  vehicleId (S)  234 non-null    object
 29  Time           219 non-null    object
 30  Speed.1        113 non-null    float64
 31  note           279 non-null    object
 32   name          44 non-null     object
 33  rpm            139 non-null    object
 34   name.1        44 non-null     object
 35  rpm.1          33 non-null     float64
 36  time           95 non-null     object
 37  speed          95 non-null     float64
 38  894            94 non-null     float64
 39  RPM            94 non-null     object
 40  speed.1        61 non-null     float64
 41  time.1         62 non-null     object
 42  speed.2        61 non-null     float64
 43  Unnamed: 15    34 non-null     float64
 44  Speed (km/h)   62 non-null     float64
 45  Engine RPM     62 non-null     float64
 46  Unnamed: 19    1 non-null      float64
 47  name           68 non-null     object
 48  Unnamed: 13    1 non-null      object
dtypes: float64(30), object(19)
memory usage: 394.4+ KB

## Missing Value

In [5]:
print(df.isnull().sum())

lat               429
lng               429
name              787
source_file         0
Unnamed: 3       1030
Unnamed: 4       1030
Unnamed: 5        996
Unnamed: 6        935
Unnamed: 7        935
Unnamed: 8        935
Unnamed: 9       1030
Unnamed: 10      1030
Unnamed: 11      1030
MAF               942
DateTime          942
Speed             829
GPH               986
LPH               986
Unnamed: 12      1028
KPL               986
Unnamed: 14       996
CO2 Emissions     986
timeStamp (N)     796
DateTime (S)      796
altitude (N)      796
latitude (N)      735
longitude (N)     701
readings (M)      656
vehicleId (S)     796
Time              811
Speed.1           917
note              751
 name             986
rpm               891
 name.1           986
rpm.1             997
time              935
speed             935
894               936
RPM               936
speed.1           969
time.1            968
speed.2           969
Unnamed: 15       996
Speed (km/h)      968
Engine RPM        968
Unnamed: 19      1029
name              962
Unnamed: 13      1029
dtype: int64

## Mengisi Missing Value

In [6]:
numeric_columns = df.select_dtypes(include=np.number).columns

df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].median())

print(df.isnull().sum())

lat                 0
lng                 0
name              787
source_file         0
Unnamed: 3       1030
Unnamed: 4       1030
Unnamed: 5          0
Unnamed: 6        935
Unnamed: 7          0
Unnamed: 8          0
Unnamed: 9       1030
Unnamed: 10      1030
Unnamed: 11      1030
MAF                 0
DateTime          942
Speed               0
GPH                 0
LPH                 0
Unnamed: 12      1028
KPL                 0
Unnamed: 14         0
CO2 Emissions       0
timeStamp (N)       0
DateTime (S)      796
altitude (N)        0
latitude (N)        0
longitude (N)     701
readings (M)      656
vehicleId (S)     796
Time              811
Speed.1             0
note              751
 name             986
rpm               891
 name.1           986
rpm.1               0
time              935
speed               0
894                 0
RPM               936
speed.1             0
time.1            968
speed.2             0
Unnamed: 15         0
Speed (km/h)        0
Engine RPM          0
Unnamed: 19         0
name              962
Unnamed: 13      1029
dtype: int64

## Menghapus Data Duplikat

In [7]:
print("Sebelum :", df.shape)

df = df.drop_duplicates()

print("Sesudah :", df.shape)

Sebelum : (1030, 49)
Sesudah : (1029, 49)

## Mengubah DateTime menjadi Format Waktu

In [10]:
df["DateTime"] = pd.to_datetime(df["DateTime"])

df.head()

,lat,lng,name,source_file,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,MAF,DateTime,Speed,GPH,LPH,Unnamed: 12,KPL,Unnamed: 14,CO2 Emissions,timeStamp (N),DateTime (S),altitude (N),latitude (N),longitude (N),readings (M),vehicleId (S),Time,Speed.1,note,name,rpm,name.1,rpm.1,time,speed,894,RPM,speed.1,time.1,speed.2,Unnamed: 15,Speed (km/h),Engine RPM,Unnamed: 19,name,Unnamed: 13
0,33.997577,71.491204,6:44:00 PM,1.csv,NaN,NaN,23.0,NaN,71.458425,25.0,NaN,NaN,NaN,3.58,NaT,23.0,2.8819,10.807125,NaN,1.035469,23.0,1.495871,1.560000e+12,NaN,329.383911,33.997574,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,1263.0,NaN,25.0,1258.0,NaN,26.0,NaN,26.0,1258.5,25.0,1254.5,989.0,NaN,NaN
1,33.997541,71.490413,6:44:00 PM,1.csv,NaN,NaN,23.0,NaN,71.458425,25.0,NaN,NaN,NaN,3.58,NaT,23.0,2.8819,10.807125,NaN,1.035469,23.0,1.495871,1.560000e+12,NaN,329.383911,33.997574,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,1263.0,NaN,25.0,1258.0,NaN,26.0,NaN,26.0,1258.5,25.0,1254.5,989.0,NaN,NaN
2,33.997589,71.489618,6:44:00 PM,1.csv,NaN,NaN,23.0,NaN,71.458425,25.0,NaN,NaN,NaN,3.58,NaT,23.0,2.8819,10.807125,NaN,1.035469,23.0,1.495871,1.560000e+12,NaN,329.383911,33.997574,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,1263.0,NaN,25.0,1258.0,NaN,26.0,NaN,26.0,1258.5,25.0,1254.5,989.0,NaN,NaN
3,33.997596,71.489163,6:45:00 PM,1.csv,NaN,NaN,23.0,NaN,71.458425,25.0,NaN,NaN,NaN,3.58,NaT,23.0,2.8819,10.807125,NaN,1.035469,23.0,1.495871,1.560000e+12,NaN,329.383911,33.997574,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,1263.0,NaN,25.0,1258.0,NaN,26.0,NaN,26.0,1258.5,25.0,1254.5,989.0,NaN,NaN
4,33.997798,71.483814,6:45:00 PM,1.csv,NaN,NaN,23.0,NaN,71.458425,25.0,NaN,NaN,NaN,3.58,NaT,23.0,2.8819,10.807125,NaN,1.035469,23.0,1.495871,1.560000e+12,NaN,329.383911,33.997574,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,1263.0,NaN,25.0,1258.0,NaN,26.0,NaN,26.0,1258.5,25.0,1254.5,989.0,NaN,NaN

## Feature Selection

In [11]:
features = [
    "lat",
    "lng",
    "MAF",
    "Speed",
    "GPH",
    "LPH",
    "KPL",
    "CO2 Emissions"
]

X = df[features]

X.head()

,lat,lng,MAF,Speed,GPH,LPH,KPL,CO2 Emissions
0,33.997577,71.491204,3.58,23.0,2.8819,10.807125,1.035469,1.495871
1,33.997541,71.490413,3.58,23.0,2.8819,10.807125,1.035469,1.495871
2,33.997589,71.489618,3.58,23.0,2.8819,10.807125,1.035469,1.495871
3,33.997596,71.489163,3.58,23.0,2.8819,10.807125,1.035469,1.495871
4,33.997798,71.483814,3.58,23.0,2.8819,10.807125,1.035469,1.495871

## Normalisasi Data

In [12]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled,
                        columns=features)

X_scaled.head()

,lat,lng,MAF,Speed,GPH,LPH,KPL,CO2 Emissions
0,0.478759,2.143419,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618
1,0.474486,2.079248,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618
2,0.480184,2.014739,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618
3,0.480997,1.977785,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618
4,0.504587,1.543742,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618

## Membuat Label Anomaly

In [13]:
df["Anomaly"] = (
    (df["Speed"] > 120) |
    (df["MAF"] > df["MAF"].quantile(0.99)) |
    (df["CO2 Emissions"] > df["CO2 Emissions"].quantile(0.99))
).astype(int)

df["Anomaly"].value_counts()

Anomaly
0    1011
1      18
Name: count, dtype: int64

## Menggabungkan Data Hasil Scaling

In [14]:
processed_data = X_scaled.copy()

processed_data["Anomaly"] = df["Anomaly"]

processed_data.head()

,lat,lng,MAF,Speed,GPH,LPH,KPL,CO2 Emissions,Anomaly
0,0.478759,2.143419,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618,0.0
1,0.474486,2.079248,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618,0.0
2,0.480184,2.014739,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618,0.0
3,0.480997,1.977785,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618,0.0
4,0.504587,1.543742,-0.151663,-0.052813,-0.106631,-0.106631,-0.059635,-0.039618,0.0

## Menyimpan Dataset

In [15]:
processed_data.to_csv(
    "../Datasheet/OBD-Anomaly-Detection/dataset/preprocessing.csv",
    index=False
)

print("Preprocessing selesai.")

Preprocessing selesai.

## Menampilkan Distribusi Label

In [16]:
print(processed_data["Anomaly"].value_counts())

print("\nPersentase:")

print(processed_data["Anomaly"].value_counts(normalize=True) * 100)

Anomaly
0.0    1010
1.0      18
Name: count, dtype: int64

Persentase:
Anomaly
0.0    98.249027
1.0     1.750973
Name: proportion, dtype: float64

Mengapa preprocessing ini penting?

* Membersihkan data dari nilai kosong dan duplikasi agar model tidak bias.
* Menyamakan skala fitur menggunakan StandardScaler sehingga algoritma berbasis jarak dan pohon bekerja lebih stabil.
* Membuat pseudo-label anomali sebagai dasar pelatihan model Random Forest karena dataset OBD-II tidak menyediakan label anomali secara langsung.
* Menghasilkan dataset yang konsisten dan siap digunakan pada tahap Isolation Forest dan Random Forest.